# -*- coding: utf-8 -*-
"""QS_Gone_Spectrophotometry.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1b9eHewtoyJFNX0ZYhaD2Hf3O4UO37PUD
"""

"""
Yasuhiko Komatsu
"""


# Get info
# add path to the Google Colab notebook
from google.colab import drive
drive.mount('/content/drive/')
import os
import sys
dataset_path = '/content/drive/My Drive/BME 590 Biotech Design Projects/Spring Semester/'


import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

Spectrometry_data = pd.read_csv(dataset_path+"QS_Gone_Spectrophotometry.csv")

Wavelength = np.array(Spectrometry_data.iloc[:,0])
Blank_1 = np.array(Spectrometry_data.iloc[:,1])
Blank_2 = np.array(Spectrometry_data.iloc[:,2])
DHL_1 = np.array(Spectrometry_data.iloc[:,3])
DHL_2 = np.array(Spectrometry_data.iloc[:,4])
DHL_3 = np.array(Spectrometry_data.iloc[:,5])
PON2_1 = np.array(Spectrometry_data.iloc[:,6])
PON2_2 = np.array(Spectrometry_data.iloc[:,7])
PON2_3 = np.array(Spectrometry_data.iloc[:,8])
DHL_PON2_1 = np.array(Spectrometry_data.iloc[:,9])
DHL_PON2_2 = np.array(Spectrometry_data.iloc[:,10])
DHL_PON2_3 = np.array(Spectrometry_data.iloc[:,11])
NaOH = np.array(Spectrometry_data.iloc[:,12])
DHL_NaOH_1 = np.array(Spectrometry_data.iloc[:,13])
DHL_NaOH_2 = np.array(Spectrometry_data.iloc[:,14])
DHL_NaOH_3 = np.array(Spectrometry_data.iloc[:,15])

#%%
DHL = np.mean([DHL_1, DHL_2, DHL_3], axis = 0)
PON2 = np.mean([PON2_1, PON2_2, PON2_3], axis = 0)
DHL_PON2 = np.mean([DHL_PON2_1, DHL_PON2_2, DHL_PON2_3], axis = 0)
DHL_NaOH = np.mean([DHL_NaOH_1, DHL_NaOH_2, DHL_NaOH_3], axis = 0)

#%%
fig = plt.figure(num = 1, clear = True) #create figure
ax = fig.add_subplot(1,1,1) #create subplot
fig, ax = plt.subplots(figsize=(8, 3))
ax.grid(True)
ax.plot(Wavelength, DHL, label = 'DHL')
ax.plot(Wavelength, PON2, label = 'PON2')
ax.plot(Wavelength, NaOH, label = 'NaOH')
ax.plot(Wavelength, DHL_PON2, label = 'DHL with PON2')
ax.plot(Wavelength, DHL_NaOH, label = 'DHL with NaOH')
plt.xlabel('wavelength (nm)') #x label
plt.ylabel('absorption (-)') #y label
ax.legend(loc='upper center', bbox_to_anchor=(1.2, 0.6), ncol=1)
fig.tight_layout() #tight layout
fig.savefig("QS_Gone_Spectrophotometry.png", bbox_inches='tight', dpi=1000)

# Focus on only data at 290 nm
abs290_df = Spectrometry_data[Spectrometry_data['Wavelength nm.']==290]

abs290_df.to_excel(dataset_path+'lactoneabs290nm.xlsx')